### ISSUE TITLE
Please make an official release

### ISSUE THREAD

**Issue by jdeligt** [mikldk/mitolina#2]
The current repository does not have an official release.
Please make one so that people have a stable version to download/use.

**Comment by mikldk** [comment]
Thanks. Done, see [here](https://github.com/mikldk/mitolina/releases).

**Comment by eugeniadamato** [comment]
I followed the first lines in the site, but I get the message 
No vignettes found by browseVignettes(package = "mitolina")

**Comment by mikldk** [comment]
@eugeniadamato Thanks for reporting this. I have updated the `README`. Please try this (with an additional `build_vignettes` argument):
``` r
# install.packages("remotes")
remotes::install_github("mikldk/mitolina", 
                        build_opts = c("--no-resave-data", "--no-manual"), 
                        build_vignettes = TRUE)
```
